version: '3'

services:
  factorem-assessment:
    build: .
    image: factorem-assessment
    environment:
      - NODE_ENV=PROD
    ports:
      - '3000:3000'
    depends_on:
      - mysql-db
    volumes:
      - .:/usr/src/factorem-assessment
    networks:
      - factorem-network

  mysql-db:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=factorem
      - MYSQL_ROOT_PASSWORD=secretpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - factorem-network

volumes:
  db_data:

networks:
  factorem-network:
    driver: bridge
