version: '3'

services:
  app:
    build: .
    image: factorem-assignment
    environment:
      - NODE_ENV=PROD
      - BASE_NAME=/api/v1
      - JWT_SECRET=factorem
      - JWT_ACCESS_EXPIRATION_MINUTES=1440
      - JWT_REFRESH_EXPIRATION_DAYS=30
      - DB_NAME=factorem
      - DB_HOST=mysql-db
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=secretpassword
    ports:
      - '3000:3000'
    depends_on:
      - mysql-db
    volumes:
      - .:/usr/src/factorem-assignment
    networks:
      - factorem-network

  mysql-db:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=factorem
      - MYSQL_ROOT_PASSWORD=secretpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - factorem-network

volumes:
  db_data:

networks:
  factorem-network:
    driver: bridge
