export const PERMISSION_ENUM = {
  CREATE_PROJECT: 'CREATE_PROJECT',
  VIEW_PROJECT: 'VIEW_PROJECT',
  UPDATE_PROJECT: 'UPDATE_PROJECT',
  DELETE_PROJECT: 'DELETE_PROJECT',
  CREATE_QUOTATION: 'CREATE_QUOTATION',
  VIEW_QUOTATION: 'VIEW_QUOTATION',
  UPDATE_QUOTATION: 'UPDATE_QUOTATION',
  DELETE_QUOTATION: 'DELETE_QUOTATION',
  ACCEPT_QUOTATION: 'ACCEPT_QUOTATION',

  MANAGE_USER: 'MANAGE_USER',
  MANAGE_QUOTATION: 'MANAGE_QUOTATION',
  MANAGE_PROJECT: 'MANAGE_PROJECT',
};

export const ROLE_ENUM = {
  CUSTOMER: 'CUSTOMER',
  SUPPLIER: 'SUPPLIER',
  ADMIN: 'ADMIN',
};

const rolePermissionMapping = {
  [ROLE_ENUM['CUSTOMER']]: [
    PERMISSION_ENUM.CREATE_PROJECT,
    PERMISSION_ENUM.VIEW_PROJECT,
    PERMISSION_ENUM.UPDATE_PROJECT,
    PERMISSION_ENUM.ACCEPT_QUOTATION
  ],
  [ROLE_ENUM['SUPPLIER']]: [
    PERMISSION_ENUM.VIEW_PROJECT,
    PERMISSION_ENUM.CREATE_QUOTATION,
    PERMISSION_ENUM.VIEW_QUOTATION,
    PERMISSION_ENUM.UPDATE_QUOTATION,
  ],
  [ROLE_ENUM['ADMIN']]: [
    PERMISSION_ENUM.MANAGE_USER,
    PERMISSION_ENUM.MANAGE_QUOTATION,
    PERMISSION_ENUM.MANAGE_PROJECT
  ],
};

export const LIST_ROLE = Object.keys(rolePermissionMapping);
export const ROLE_PERMISSION = new Map(Object.entries(rolePermissionMapping));
